version: '3'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-analytics-api
    restart: unless-stopped
    user: root
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - ianalytics-admin_app_network
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-analytics-api
    restart: unless-stopped
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - ianalytics-admin_app_network

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.25.2
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      - ianalytics-admin_app_network
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped


  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    labels:
      NAME: "rabbitmq"
    networks:
      - ianalytics-admin_app_network
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  redis:
    image: redis:4.0
    container_name: ianalytics_redis
    ports:
      - "6382:6379"
    networks:
      - ianalytics-admin_app_network

volumes:
  dbdata:

networks:
  ianalytics-admin_app_network:
    external: true

