version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-analytics-api
    restart: unless-stopped
    user: root
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - ianalyticsadmin_app_network
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-analytics-api
    restart: unless-stopped
    ports:
    - "8001:80"   # Use a different host port, like 8080, for example
    - "443:443"  # Use a different host port, like 8443, for example
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - ianalyticsadmin_app_network

volumes:
  dbdata:

networks:
  ianalyticsadmin_app_network:
    external: true

